In [ ]:
from src    import data_loader
from src import pitcher_attributes, pitcher_rating, batter_attributes

#display(data_loader.get_fangraphs(2025))
#a = data_loader.get_player("Shohei", "Ohtani")
#print(a)
#display(pitcher_attributes.get_war(int(a), 2025))

#display(pitcher_attributes.get_whif(data_loader.get_season_pitching(2025)))
#display(data_loader.get_batting())
display(batter_attributes.get_contact(2025))
display(data_loader.get_player('Ronald', 'Acuna jr'))
display(data_loader.get_season_pitching(2024))
display(data_loader.get_batting_year(2024))

,"last_name, first_name",year,player_id,contact_score,batting_avg,bat_control_score,hit_score,hit_measure
2648,"Maldonado, Martín",2025,455117,0.02,0.204,2.798982,5.343511,0.1980
2649,"Solano, Donovan",2025,456781,0.35,0.247,51.399491,34.732824,0.2350
2650,"McCutchen, Andrew",2025,457705,0.49,0.239,30.279898,56.743003,0.2485
2651,"Turner, Justin",2025,457759,0.37,0.219,87.531807,25.699746,0.2280
2652,"Santana, Carlos",2025,467793,0.21,0.219,47.328244,17.684478,0.2175
...,...,...,...,...,...,...,...,...
3036,"Shaw, Matt",2025,807713,0.38,0.226,75.318066,29.898219,0.2315
3037,"Yoshida, Masataka",2025,807799,0.91,0.266,87.786260,83.587786,0.2680
3038,"Kim, Hyeseong",2025,808975,0.52,0.280,28.244275,59.923664,0.2505
3039,"Lee, Jung Hoo",2025,808982,0.93,0.266,95.674300,85.623410,0.2715
3040,"Williamson, Ben",2025,810938,0.61,0.253,70.737913,55.089059,0.2470

No identically matched names found! Returning the 5 most similar names.

np.int64(660670)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
598,CH,2024-10-01,88.1,-1.65,6.12,"Brieske, Beau",518792,689225,field_out,hit_into_play,...,1,2.5,1.4,-1.4,46.4,21.481595,-17.851272,24.228579,43.236189,31.25396
611,CH,2024-10-01,87.1,-1.69,6.17,"Brieske, Beau",518792,689225,NaN,swinging_strike,...,1,2.45,1.19,-1.19,44.1,14.52903,-35.809638,19.463062,61.68396,44.906197
639,CH,2024-10-01,89.7,-1.89,6.14,"Brieske, Beau",518792,689225,NaN,ball,...,1,2.44,1.33,-1.33,47.4,<NA>,<NA>,<NA>,<NA>,<NA>
660,FF,2024-10-01,97.5,-1.51,6.32,"Brieske, Beau",518792,689225,NaN,foul,...,1,0.82,0.4,-0.4,55.0,7.804441,0.738715,22.363442,50.109329,18.509113
678,CH,2024-10-01,88.6,-1.77,6.19,"Brieske, Beau",518792,689225,NaN,blocked_ball,...,1,2.32,1.3,-1.3,47.0,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3209,CU,2024-03-28,78.0,-2.24,5.69,"Eovaldi, Nathan",641355,543135,NaN,called_strike,...,2,4.52,-0.64,0.64,34.6,<NA>,<NA>,<NA>,<NA>,<NA>
3401,FF,2024-03-28,96.7,-2.41,5.34,"Eovaldi, Nathan",673548,543135,field_out,hit_into_play,...,2,1.28,1.07,1.07,28.3,<NA>,<NA>,<NA>,<NA>,<NA>
3443,CU,2024-03-28,78.1,-2.27,5.62,"Eovaldi, Nathan",673548,543135,NaN,called_strike,...,2,4.82,-0.58,-0.58,32.4,<NA>,<NA>,<NA>,<NA>,<NA>
3640,FF,2024-03-28,97.0,-2.4,5.36,"Eovaldi, Nathan",673548,543135,NaN,ball,...,2,1.54,1.37,1.37,29.4,<NA>,<NA>,<NA>,<NA>,<NA>
3687,FF,2024-03-28,96.1,-2.39,5.33,"Eovaldi, Nathan",664023,543135,field_out,hit_into_play,...,2,1.51,1.18,-1.18,26.6,<NA>,<NA>,<NA>,<NA>,<NA>

,"last_name, first_name",player_id,year,player_age,ab,pa,hit,single,double,triple,...,avg_best_speed,avg_hyper_speed,z_swing_percent,z_swing_miss_percent,oz_swing_miss_percent,oz_contact_percent,iz_contact_percent,whiff_percent,swing_percent,sprint_speed
0,"Beltré, Adrian",134181,2018,39,433,481,118,79,23,1,...,98.435139,93.348635,62.3,16.9,36.6,63.4,83.1,23.4,45.4,24.9
1,"Martinez, Victor",400121,2018,39,467,508,117,87,21,0,...,96.557884,92.300796,68.5,9.3,23.9,76.1,90.7,14.3,49.2,23.2
2,"Utley, Chase",400284,2018,39,164,187,35,23,10,1,...,96.099441,92.085202,57.0,9.0,28.6,71.4,91.0,13.3,37.6,27.2
3,"Pujols, Albert",405395,2018,38,465,498,114,75,20,0,...,99.833402,94.151906,66.2,9.8,31.8,68.2,90.2,17.6,48.4,22.2
4,"Mauer, Joe",408045,2018,35,486,543,137,103,27,1,...,99.892946,94.507836,49.8,8.2,35.5,64.5,91.8,15.1,35.3,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3434,"Yoshida, Masataka",807799,2026,32,263,297,72,50,16,1,...,99.027488,93.672636,58.3,9.3,27.6,72.4,90.7,15.6,42.6,26.1
3435,"Murakami, Munetaka",808959,2026,26,428,521,87,40,14,1,...,104.209870,97.124004,61.6,33.8,64.0,36.0,66.2,42.8,40.6,26.8
3436,"Lee, Jung Hoo",808982,2026,27,537,576,148,103,31,4,...,96.875956,92.554033,63.8,6.2,25.7,74.3,93.8,12.5,47.7,27.5
3437,"Williamson, Ben",810938,2026,25,247,270,61,47,10,1,...,98.097678,93.075551,55.4,10.1,28.7,71.3,89.9,17.1,42.9,28.1
3438,"Waldschmidt, Ryan",814439,2026,23,248,282,63,44,15,1,...,97.326693,92.692202,62.2,19.5,62.0,38.0,80.5,31.6,43.5,29.1