In [2]:
from src    import data_loader
from src import pitcher_attributes, pitcher_rating, batter_attributes
import main
display(main.main()[0])
display(main.main()[1])

    year        player_name  batter Power Contact    WAR
0   2026      Riley, Austin  663586  70.0    12.0  69.36
1   2026    Hicklen, Brewer  676551  None    None  32.46
2   2026   Keirsey, Dashawn  680577  None    None  48.91
3   2026     Smith, Dominic  642086  28.0    58.0  24.21
4   2026     Baldwin, Drake  686948  82.0    89.0  94.78
5   2026      Kim, Ha-seong  673490  None    None   3.03
6   2026       Farmer, Kyle  571657  None    None  26.52
7   2026        Olson, Matt  621566  96.0    59.0  96.24
8   2026    Dubón, Mauricio  643289  18.0    94.0  87.74
9   2026    Harris, Michael  671739  83.0    94.0  97.09
10  2026  Yastrzemski, Mike  573262  51.0    36.0  71.97
11  2026      Albies, Ozzie  645277  30.0    46.0  78.40
12  2026      Acuña, Ronald  660670  87.0    67.0  83.13
13  2026       Murphy, Sean  669221  None    None  45.15

    year  pitcher  movement  velocity control    war   woba    whiff
0   2026   700363      59.0      76.0    None  56.17  14.66  38.4242
1   2026   608718      51.0       3.0  45.155  72.04  54.72  45.2121
2   2026   519242      64.0      80.0  89.031  99.37  89.74  82.7879
3   2026   800311      49.0      91.0  73.309  89.92  91.86  81.6970
4   2026   689266       1.0      37.0  79.707   77.2  90.55  80.2424
5   2026   669276      32.0      38.0  78.245  91.18  94.79  96.8485
6   2026   656550      22.0      42.0  85.375  72.17  57.49  69.9394
7   2026   702275      71.0      50.0    None  14.36  27.52  43.6364
8   2026   527048      35.0       2.0  95.795  82.62  71.99  28.9697
9   2026   702566      97.0      38.0    None  51.13   None  19.3939
10  2026   628452      64.0      55.0  99.634  80.98  79.15  80.8485
11  2026   678061      56.0      60.0    None   None   None  46.4242
12  2026   641816      28.0      25.0  99.817  86.02  56.51  40.7273
13  2026   682989      32.0      40.0  12.797  63.22   71.5  81.5758